name: Deploy to Doodlab

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy Code (Preserve data)
      run: |
        rsync -av --delete \
          --exclude='.env' \
          --exclude='data' \
          --exclude='venv' \
          --exclude='.git' \
          --exclude='www.youtube.com_cookies.txt' \
          ./ /home/dood345/discordBot/

    - name: Update Dependencies
      run: |
        # CHANGED .cargo to .local here
        if [ ! -f "$HOME/.local/bin/uv" ]; then
          curl -LsSf https://astral.sh/uv/install.sh | sh
        fi
        cd /home/dood345/discordBot/
        export UV_PROJECT_ENVIRONMENT=/home/dood345/discordBot/venv
        
        # CHANGED .cargo to .local here
        $HOME/.local/bin/uv sync --no-dev

    - name: Restart Service
      # Reload the bot so it reads the new code and the existing .env
      run: sudo systemctl restart discordBot.service
